In [8]:
#importing the required libraries
import rasterio
import numpy as np
from affine import Affine
from pyproj import Proj, transform

In [9]:
fname = '/Users/ArshiaSultana/Desktop/PS_tmax_10.tif'


In [10]:
# Read raster
with rasterio.open(fname) as r:
    T0 = r.transform  # upper-left pixel corner affine transform
    p1 = Proj(r.crs)
    A = r.read()  # pixel values


In [9]:
print(T0)

| 1000.00, 0.00, 2008250.00|
| 0.00,-1000.00, 195500.00|
| 0.00, 0.00, 1.00|


In [11]:
print(A)

[[[-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  ...
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]]

 [[-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  ...
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]]

 [[-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  ...
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]]

 ...

 [[-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -99

In [10]:
print(p1)

Proj('+proj=lcc +lat_0=42.5 +lon_0=-100 +lat_1=25 +lat_2=60 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs', preserve_units=True)


In [11]:
# All rows and columns
cols, rows = np.meshgrid(np.arange(A.shape[2]), np.arange(A.shape[1]))

In [12]:
print(A)

[[[-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  ...
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]]

 [[-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  ...
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]]

 [[-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  ...
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -9999. ... -9999. -9999. -9999.]]

 ...

 [[-9999. -9999. -9999. ... -9999. -9999. -9999.]
  [-9999. -9999. -99

In [13]:
print(cols,rows)


[[ 0  1  2 ... 50 51 52]
 [ 0  1  2 ... 50 51 52]
 [ 0  1  2 ... 50 51 52]
 ...
 [ 0  1  2 ... 50 51 52]
 [ 0  1  2 ... 50 51 52]
 [ 0  1  2 ... 50 51 52]] [[ 0  0  0 ...  0  0  0]
 [ 1  1  1 ...  1  1  1]
 [ 2  2  2 ...  2  2  2]
 ...
 [80 80 80 ... 80 80 80]
 [81 81 81 ... 81 81 81]
 [82 82 82 ... 82 82 82]]


In [14]:
print(cols)

[[ 0  1  2 ... 50 51 52]
 [ 0  1  2 ... 50 51 52]
 [ 0  1  2 ... 50 51 52]
 ...
 [ 0  1  2 ... 50 51 52]
 [ 0  1  2 ... 50 51 52]
 [ 0  1  2 ... 50 51 52]]


In [15]:
print(rows)

[[ 0  0  0 ...  0  0  0]
 [ 1  1  1 ...  1  1  1]
 [ 2  2  2 ...  2  2  2]
 ...
 [80 80 80 ... 80 80 80]
 [81 81 81 ... 81 81 81]
 [82 82 82 ... 82 82 82]]


In [16]:
# Get affine transform for pixel centres
T1 = T0 * Affine.translation(0.5, 0.5)
print(T1)

| 1000.00, 0.00, 2008750.00|
| 0.00,-1000.00, 195000.00|
| 0.00, 0.00, 1.00|


In [17]:
# Function to convert pixel row/column index (from 0) to easting/northing at centre
rc2en = lambda r, c: (c, r) * T1

In [18]:
print(rc2en)

<function <lambda> at 0x11e6f76a8>


In [19]:
# All eastings and northings (there is probably a faster way to do this)
eastings, northings = np.vectorize(rc2en, otypes=[np.float, np.float])(rows, cols)

/Users/ArshiaSultana/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: Right multiplication will be prohibited in version 3.0
  


In [20]:
print(eastings, northings)

[[2008750. 2009750. 2010750. ... 2058750. 2059750. 2060750.]
 [2008750. 2009750. 2010750. ... 2058750. 2059750. 2060750.]
 [2008750. 2009750. 2010750. ... 2058750. 2059750. 2060750.]
 ...
 [2008750. 2009750. 2010750. ... 2058750. 2059750. 2060750.]
 [2008750. 2009750. 2010750. ... 2058750. 2059750. 2060750.]
 [2008750. 2009750. 2010750. ... 2058750. 2059750. 2060750.]] [[195000. 195000. 195000. ... 195000. 195000. 195000.]
 [194000. 194000. 194000. ... 194000. 194000. 194000.]
 [193000. 193000. 193000. ... 193000. 193000. 193000.]
 ...
 [115000. 115000. 115000. ... 115000. 115000. 115000.]
 [114000. 114000. 114000. ... 114000. 114000. 114000.]
 [113000. 113000. 113000. ... 113000. 113000. 113000.]]


In [21]:
# Project all longitudes, latitudes
p2 = Proj(proj='latlong',datum='WGS84')
longs,lats = transform(p1, p2, eastings, northings)

In [22]:
print(p2)

Proj('+proj=longlat +datum=WGS84 +no_defs', preserve_units=True)


In [23]:
#storing longs,lats into an array
a=longs,lats

np.size(a)

8798

In [24]:
print(a)

(array([[-74.41777583, -74.40582467, -74.39387459, ..., -73.82155343,
        -73.80965693, -73.79776153],
       [-74.42156017, -74.40961054, -74.39766201, ..., -73.82541423,
        -73.81351924, -73.80162536],
       [-74.42534341, -74.41339533, -74.40144833, ..., -73.82927392,
        -73.81738045, -73.80548809],
       ...,
       [-74.71713305, -74.70530404, -74.69347608, ..., -74.12697475,
        -74.11519863, -74.10342357],
       [-74.72083206, -74.70900456, -74.69717811, ..., -74.13074888,
        -74.11897425, -74.10720068],
       [-74.72453001, -74.71270402, -74.70087909, ..., -74.13452195,
        -74.12274881, -74.11097673]]), array([[41.41001717, 41.40716713, 41.4043158 , ..., 41.26594383,
        41.26302974, 41.26011437],
       [41.40101942, 41.39816979, 41.39531889, ..., 41.25696724,
        41.25405357, 41.25113863],
       [41.39202157, 41.38917236, 41.38632188, ..., 41.24799055,
        41.24507731, 41.2421628 ],
       ...,
       [40.68991777, 40.68710111, 40.

In [25]:
#shape of the array(2D)
np.shape(a)

(2, 83, 53)

In [26]:
#reshaping the 2D array into 1D
b=np.reshape(a,8798)
b

array([-74.41777583, -74.40582467, -74.39387459, ...,  40.52956277,
        40.52668359,  40.52380314])

In [27]:
#shape of array b(1D)
np.shape(b)

(8798,)

In [28]:
#c=np.array_split(b,2,axis=0)
#np.shape(c)
#print(c)

In [32]:
import pandas as pd
#creating a dataframe from the array b
#selecting first 4399 values for latitude and last 4399 values for longitude (indexing)
dataset = pd.DataFrame({'LONGITUDE': b[:4399], 'LATITUDE': b[4399: ]})
dataset = dataset[['LATITUDE','LONGITUDE']]
dataset.head()


LATITUDE  LONGITUDE
0  41.410017 -74.417776
1  41.407167 -74.405825
2  41.404316 -74.393875
3  41.401463 -74.381926
4  41.398609 -74.369978

In [33]:
#saving the dataframe to csv
dataset.to_csv("Longitude and latitude_output.csv")